### ISSUE TITLE
Difficulty instantiating PersistentWebsocket

### ISSUE THREAD

**Issue by germanjoey** [phound-inc/persistent-websocket#1]
I tried replacing ReconnectingWebsocket with persistent-websocket.min.js in my project, but I can't seem to figure out how to even create a new object, much less test the rest of the functionality. 

Could you show an example of how to do this with regular Javascript?

**Comment by dougkeen** [comment]
The "plain javascript" translation of the README example would look like:

```javascript
function sendPing(pws) {
  pws.send("ping");
}

var pws = new PersistentWebsocket("ws://mysite.com/", {
  "pingSendFunction": sendPing,
  "reachabilityTestUrl": "/favicon.ico"  
});
```

**Comment by dougkeen** [comment]
Oh, and if you're pulling in the lib with a basic `<script src="persistent-websocket.min.js"></script>` tag, note that the class will be under the `persistentwebsocket` namespace, like:

```javascript
var pws = new persistentwebsocket.PersistentWebsocket("ws://mysite.com/", {
  "pingSendFunction": sendPing,
  "reachabilityTestUrl": "/favicon.ico"  
});
```

**Comment by dougkeen** [comment]
@germanjoey was this resolved? I'd like to close this if it was.
